<?php

namespace Recruiter\RecruitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EducationStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EducationStatusRepository extends EntityRepository
{
}
