<?php

namespace Recruiter\RecruitBundle\Entity;

use Recruiter\CommonBundle\Entity\UploadType;

use Doctrine\ORM\EntityRepository;

/**
 * RecruitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecruitRepository extends EntityRepository
{
	public function countAll($joinDate = 0)
	{
		$qb = $this->getEntityManager()->createQueryBuilder()
			->add('select', 'count(r.id)')
			->add('from', 'RecruiterRecruitBundle:Recruit r')
			->add('where', 'r.recruit_created_at > :join_date')
			->setParameter('join_date', $joinDate)
		;
		
		return (int) $qb->getQuery()->getSingleScalarResult();
	}
	
	public function fetchLatest($limit = 10)
	{
		$qb = $this->getEntityManager()->createQueryBuilder()
			->add('select', 'r')
			->add('from', 'RecruiterRecruitBundle:Recruit r')
			->setMaxResults($limit)
			->addOrderBy('r.recruit_created_at', 'DESC')
		;
		
		return $qb->getQuery()->getResult();
	}
	
	public function getCvs($rid, $limit = 1)
	{
		$em = $this->getEntityManager();
		$type = $em->getRepository('RecruiterCommonBundle:UploadType')
			->findBy(array('upload_type_name' => UploadType::TYPE_CV));
	
		$qb = $em->createQueryBuilder()
			->add('select', 'u')
			->add('from', 'RecruiterCommonBundle:Upload u')
			->add('where', 'u.upload_type = :type and u.recruit = :recruit')
			->add('orderBy', 'u.id DESC')
			->setParameter('type', $type)
			->setParameter('recruit', $this->find($rid))
			->setMaxResults($limit)
		;
		
		$method = ($limit == 1) ? "getSingleResult" : "getResult";
	
		return $qb->getQuery()->$method();
	}
}
